name = "gpus"
version = "0.1.0"
defaultTargets = ["gpus_tests"]

[[require]]
name = "leandb"
path = "../.."

[[lean_lib]]
name = "Gpus"

[[lean_exe]]
name = "gpus_tests"
root = "GpusTests"

[[lean_exe]]
name = "gpus"
root = "Main"
