name = "crm"
version = "0.1.0"
defaultTargets = ["crm_tests"]

[[require]]
name = "leandb"
path = "../.."

[[lean_lib]]
name = "Crm"

[[lean_exe]]
name = "crm_tests"
root = "CrmTests"

[[lean_exe]]
name = "crm"
root = "Main"
