import LeanDb.Render
import LeanDb.Migration

namespace LeanDb.Freeze

/-! # `migrate freeze`: the schema history as source

Freezing version `n` writes `<Module>/Migrations/V<n>.lean` — the schema
snapshot as data (`V<n>.schema`), one raw structure per table (the row
as stored: `Int64`/`String`/`Float`, `Option` when nullable), and for
`n ≥ 1` the migration `M<n>` from `V<n-1>`: mechanical steps need
nothing; every table the diff refuses gets a `Step.transformT` whose body
is a `sorry` hole naming the reason, so the file compiles into the TODO
list and the build is green only once the judgment is written. The
roll-up `<Module>/Migrations.lean` (regenerated every time) defines
`chain`. -/

structure Target where
  module : String
  /-- Directory of the version files, relative to the package root. -/
  dir : System.FilePath
  /-- Modules that bring the head entity types into scope. -/
  imports : List String

def Target.ofModule (module : String) (imports : List String := []) : Target :=
  { module, dir := module / "Migrations",
    imports := if imports.isEmpty then [s!"{module}.Entities"] else imports }

private def header (base : String) : String :=
  s!"/- Generated by `{base} migrate freeze`. The snapshot and the raw types are\n" ++
  "   data: do not edit them. The migration below is yours: fill its holes. -/\n"

/-- The raw structure of a table as stored at this version. -/
private def rawStruct (t : TableSpec) : String :=
  let fields := t.columns.toList.map fun c =>
    s!"  {Render.fieldName c.name} : {Render.rawType c}"
  String.intercalate "\n" <|
    [s!"/-- `{t.name}` as stored at this version (`id` excluded). -/",
     s!"structure {Render.typeIdent t.name} where"] ++
    (if fields.isEmpty then ["  mk ::"] else fields) ++
    ["  deriving Repr, LeanDb.Entity"]

/-- Tables the mechanical diff refuses, each with the reason, found by
    covering one table at a time until the plan goes through. -/
def refusals (prev new : List TableSpec) : List (String × String) := Id.run do
  let mut covered : List String := []
  let mut out : List (String × String) := []
  for _ in [0:new.length + 1] do
    match planMigration prev new covered with
    | .ok _ => break
    | .error msg =>
        match refusedTable? msg with
        | some t =>
            if covered.contains t then break
            covered := covered ++ [t]
            out := out ++ [(t, msg)]
        | none => break
  return out
where
  /-- Refusals are phrased `table "<name>": …`. -/
  refusedTable? (msg : String) : Option String :=
    if msg.startsWith "table \"" then
      let rest := (msg.drop 7).toString
      some ((rest.takeWhile (· != '"')).toString)
    else none

/-- The migration definition for version `n ≥ 1`. -/
private def migrationDef (n : Nat) (prev new : List TableSpec)
    (typeNames : List (String × String)) : String × Nat :=
  let holes := refusals prev new
  let stepLines := holes.map fun (t, why) =>
    let oldTy := s!"V{n-1}.{Render.typeIdent t}"
    let newTy := (typeNames.lookup t).getD (Render.typeIdent t)
    String.intercalate "\n" [
      s!"    -- {why}",
      s!"    LeanDb.Step.transformT {oldTy} {newTy} fun (old : {oldTy}) =>",
      s!"      sorry"]
  let steps := if stepLines.isEmpty then "[]" else
    "[\n" ++ String.intercalate ",\n" stepLines ++ "]"
  let src := String.intercalate "\n" [
    s!"/-- V{n-1} → V{n}. The mechanical steps are diffed from the two snapshots at",
    "    apply time; the steps below are the judgments the diff could not make.",
    (if holes.isEmpty then "    Nothing needed judgment here. -/"
     else s!"    {holes.length} hole(s): each `sorry` is a typed transform to write. -/"),
    s!"def M{n} : LeanDb.Migration := \{",
    s!"  fromFingerprint := {String.quote (fingerprint prev)}",
    s!"  toFingerprint := {String.quote (fingerprint new)}",
    s!"  snapshot := V{n}.schema",
    s!"  steps := {steps}",
    "}"]
  (src, holes.length)

/-- The version file. Returns the source and the number of holes. -/
def versionFile (t : Target) (base : String) (n : Nat) (specs : List TableSpec)
    (prev : Option (List TableSpec)) (typeNames : List (String × String)) : String × Nat :=
  let imports := "import LeanDb" ::
    (if n == 0 then [] else s!"import {t.module}.Migrations.V{n - 1}" :: t.imports.map ("import " ++ ·))
  let (mig, holes) := match prev with
    | some p => migrationDef n p specs typeNames
    | none => ("", 0)
  let head : List String := imports ++ ["", header base, s!"namespace {t.module}.Migrations", "",
      s!"namespace V{n}", "",
      s!"/-- The schema at version {n}: fingerprint `{fingerprint specs}`. -/",
      s!"def schema : List LeanDb.TableSpec :=",
      s!"  {Render.specsLit specs}", ""]
  let structs : List String := (specs.map rawStruct).intersperse ""
  let tail : List String := ["", s!"end V{n}"] ++
    (if mig.isEmpty then [] else ["", mig]) ++
    ["", s!"end {t.module}.Migrations", ""]
  let src := String.intercalate "\n" (head ++ structs ++ tail)
  (src, holes)

/-- The roll-up: imports every version and defines `chain`. -/
def rollup (t : Target) (base : String) (head : Nat) : String :=
  let imports := (List.range (head + 1)).map fun k => s!"import {t.module}.Migrations.V{k}"
  let migs := (List.range head).map fun k => s!"M{k + 1}"
  String.intercalate "\n" <| imports ++ ["",
    s!"/- Generated by `{base} migrate freeze`; regenerated on every freeze. -/", "",
    s!"namespace {t.module}.Migrations", "",
    "/-- The base's schema history: the origin and every migration after it. -/",
    "def chain : LeanDb.Chain := {",
    "  origin := V0.schema",
    s!"  migrations := [{String.intercalate ", " migs}]",
    "}", "",
    s!"end {t.module}.Migrations", ""]

end LeanDb.Freeze
