name = "legacy"
version = "0.1.0"
defaultTargets = ["legacy", "legacy_tests"]

[[require]]
name = "leandb"
path = "../.."

[[lean_lib]]
name = "Legacy"

[[lean_exe]]
name = "legacy"
root = "Main"

[[lean_exe]]
name = "legacy_tests"
root = "LegacyTests"
