import Legacy

/- Generated by `leandb import-sqlite`. Edit freely — this file is yours
   now; the importer never regenerates over it. -/

/-! The legacy CLI: `LeanDb.Cli.run` over the base value. -/

def main (args : List String) : IO UInt32 :=
  LeanDb.Cli.run Legacy.base args
