import Legacy

/- Generated by `leandb import-sqlite`. Edit freely — this file is yours
   now; the importer never regenerates over it. -/

/-! The legacy CLI: `LeanDb.Cli.run` over the imported entities. -/

def main (args : List String) : IO UInt32 :=
  LeanDb.Cli.run {
    name := "legacy"
    dbPath := System.FilePath.mk "data/legacy.db"
    specs := Legacy.schema
    tables := [.of Legacy.Customers, .of Legacy.Orders]
  } args
