import Legacy.Entities
import Legacy.Migrations

/- Generated by `leandb import-sqlite`. Edit freely — this file is yours
   now; the importer never regenerates over it. -/

/-! The legacy base as a value: tables (the schema is derived from
them), queries, and the default instance path. Other packages that
import `Legacy` get this value along with the types. -/

namespace Legacy

def base : LeanDb.Base := {
  name := "legacy"
  module := "Legacy"
  tables := [.of Customers, .of Orders]
  defaultDb := some (System.FilePath.mk "data/legacy.db")
  chain := some Migrations.chain
}

end Legacy
