import LeanDb
import Legacy.Scalars

/- Generated by `leandb import-sqlite`. Edit freely — this file is yours
   now; the importer never regenerates over it. -/

namespace Legacy

/-- Imported from table `customers` (`id` is LeanDB's, not a field). -/
structure Customers where
  name : CustomersName
  email : Option CustomersEmail
  balance : Float
  deriving Repr, LeanDb.Entity

/-- V1 (hand-tightened after the import): the closed world the uncarried
    `big_orders` view (`qty > 10`) encoded as a filter. -/
inductive OrderSize where
  | small | bulk
  deriving Repr, DecidableEq, Ord, LeanDb.ClosedEnum

/-- Imported from table `orders` (`id` is LeanDB's, not a field). At V1
    `qty : Int64` became `size : OrderSize` — see `Legacy/Migrations/V1.lean`
    for the typed transform that carried the rows. -/
structure Orders where
  customer_id : LeanDb.Ref Customers
  item : OrdersItem
  size : OrderSize
  deriving Repr, LeanDb.Entity

/-- FK-dependency order: referenced tables first. -/
def schema : List LeanDb.TableSpec :=
  [LeanDb.Entity.spec Customers, LeanDb.Entity.spec Orders]

end Legacy
