import LeanDb
import Legacy.Scalars

/- Generated by `leandb import-sqlite`. Edit freely — this file is yours
   now; the importer never regenerates over it. -/

namespace Legacy

/-- Imported from table `customers` (`id` is LeanDB's, not a field). -/
structure Customers where
  name : CustomersName
  email : Option CustomersEmail
  balance : Float
  deriving Repr, LeanDb.Entity

/-- Imported from table `orders` (`id` is LeanDB's, not a field). -/
structure Orders where
  customer_id : LeanDb.Ref Customers
  item : OrdersItem
  qty : Int64
  deriving Repr, LeanDb.Entity

/-- FK-dependency order: referenced tables first. -/
def schema : List LeanDb.TableSpec :=
  [LeanDb.Entity.spec Customers, LeanDb.Entity.spec Orders]

end Legacy
