import Legacy.Migrations.V0
import Legacy.Migrations.V1

/- Generated by `legacy migrate freeze`; regenerated on every freeze. -/

namespace Legacy.Migrations

/-- The base's schema history: the origin and every migration after it. -/
def chain : LeanDb.Chain := {
  origin := V0.schema
  migrations := [M1]
}

end Legacy.Migrations
