import LeanDb

/- Generated by `leandb import-sqlite`. Edit freely — this file is yours
   now; the importer never regenerates over it. -/

/-! # Scalars: one named newtype per imported text column.

Import loose, tighten forever (plan.md §5.1): each `make` validates
nothing yet; every future validation is one edit away. -/

namespace Legacy

/-- `customers.name` (declared `TEXT`). Identity validator — tighten here. -/
structure CustomersName where
  raw : String
  deriving Repr, DecidableEq

def CustomersName.make : String → Except String CustomersName :=
  .ok ∘ CustomersName.mk

instance : LeanDb.ColCodec CustomersName :=
  LeanDb.ColCodec.via (·.raw) CustomersName.make

/-- `customers.email` (declared `TEXT`). Identity validator — tighten here. -/
structure CustomersEmail where
  raw : String
  deriving Repr, DecidableEq

def CustomersEmail.make : String → Except String CustomersEmail :=
  .ok ∘ CustomersEmail.mk

instance : LeanDb.ColCodec CustomersEmail :=
  LeanDb.ColCodec.via (·.raw) CustomersEmail.make

/-- `orders.item` (declared `TEXT`). Identity validator — tighten here. -/
structure OrdersItem where
  raw : String
  deriving Repr, DecidableEq

def OrdersItem.make : String → Except String OrdersItem :=
  .ok ∘ OrdersItem.mk

instance : LeanDb.ColCodec OrdersItem :=
  LeanDb.ColCodec.via (·.raw) OrdersItem.make

end Legacy
