name = "shop"
version = "0.1.0"
defaultTargets = ["shop_tests"]

[[require]]
name = "leandb"
path = "../.."

[[lean_lib]]
name = "Shop"

[[lean_exe]]
name = "shop_tests"
root = "ShopTests"

[[lean_exe]]
name = "shop"
root = "Main"
